#!/usr/bin/env python

import roslib; roslib.load_manifest('strands_datacentre')
import rospy

import strands_datacentre.util
import strands_diagnostics

if __name__=="__main__":
    # start the logger
    node =  rospy.init_node("diagnostics_logger")
    logger = strands_diagnostics.DiagnosticsLogger(node)