#!/usr/bin/env python

import roslib; roslib.load_manifest('ros_datacentre')
import rospy

import ros_datacentre.util
from strands_diagnostics.logger import DiagnosticsLogger

if __name__=="__main__":
    # start the logger
    node =  rospy.init_node("diagnostics_logger")
    logger = DiagnosticsLogger(node)